#!/usr/bin/env bash
set -euo pipefail

# Install Diego Valle's dotfiles
# https://github.com/diegovalle/dotfiles

git clone --recurse-submodules --bare \
    https://github.com/diegovalle/dotfiles.git "$HOME"/.dotfiles
dotfiles() {
   git --git-dir="$HOME"/.dotfiles/ --work-tree="$HOME" "$@"
}

# Need to chekout emacs submodule
if dotfiles checkout && ( cd .emacs.d && \
        dotfiles submodule update --init --recursive );
  then
    echo "Cloned dotfiles"
  else
    echo "Backing up pre-existeing files to ~/.dotfiles-backup"
    mkdir -p "$HOME"/.dotfiles-backup
    (dotfiles checkout 2>&1 || true) | grep -E "^\s+" | awk '{print $1}' | \
        xargs -I{} mv "$HOME"/{} "$HOME"/.dotfiles-backup/{}
    if [ -d "$HOME"/.emacs.d ]; then
        mv -R "$HOME"/.emacs.d "$HOME"/.dotfiles-backup
    fi
    dotfiles checkout
    ( cd .emacs.d && dotfiles submodule update --init --recursive )
fi;

dotfiles config status.showUntrackedFiles no
